name: Changes in Staging Labeler

on:
  push:
    branches:
      - staging

jobs:
  labelPrChangesInBranch:
    runs-on: ubuntu-latest

    steps:
    - uses: chrishanthmathew91/actions/dist/changes_in_branch_labeler@feature/add-colors
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        target-branch: staging
