name: Pull Request Labeler

on: [pull_request]

jobs:
  labelPRs:
    runs-on: ubuntu-latest

    steps:
      - uses: chrishanthmathew91/actions/dist/pull_request_labeler@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          required: 2
          wip: false
          target-branch: staging
          label: Changes in staging
          color: 8989FF
