name: Pull Request Labeler

on: [pull_request]

jobs:
  labelPRs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/dist/pull_request_labeler@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}