name: Pull Request Labeler

on: [push]

jobs:
  labelPRs:
    runs-on: ubuntu-latest

    steps:
    - uses: chrishanthmathew91/actions/dist/pull_request_labeler@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}