name: Translations diff check

on: [pull_request]

jobs:
  translation-check:
    runs-on: ubuntu-latest

    steps:
      - uses: chrishanthmathew91/actions/dist/translations_diff@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: main
          target-branch: feature
